#!/bin/sh

case $1 in
	
	install)
		echo "Installing $2"
		cp $2 /teaOS/modules/mods/
		$2
		echo "Finished installing $2"
;;

	view)
		cd /teaOS/modules/view
		less ./$2
;;
	rm)
		echo "Uninstalling $2"
		cd /teaOS/modules/mods/
		cd $2
		./uninstall
		echo "Finished uninstalling $2"
;;
	help)
		echo "mod:"
		echo ""
		echo "		install: Installs mod file"
		echo "		view:    Views mod file"
		echo "		rm:      Removes mod"
		echo ""
esac
