#!/bin/sh
if  [[ $1 = "-isdvvffvwervwervew" ]]; then
    
	// the code that does stuff

	echo "Option -o turned on"
else

	clear
	ls *.img *.iso 2> /dev/null
	echo "Enter name of ISO:" && read iso
	clear
	lsblk
	echo "Enter filename of the device:" && read dev
	dd if=$iso | pv | dd of=$dev 2> /dev/null

fi	


