#!/bin/sh

case $1 in
	help)
		
		tea-help
;;
		
	ver)
		
		version
;;
	id)
		/teaOS/sys/id
;;
	"")
		echo "tea ARGS"
		echo "		"
		echo "		ver:  Shows teaOS Version"
		echo "		help: Runs tea-help"
		echo "		id:   Shows teaOS ID"
		echo ""
;;

esac	
