#!/bin/sh
echo "Type --help for help"
if  [[ $1 = "--mit" ]]; then 

	cat /teaOS/utils/license/licenses/mit
else
	break
fi	

if [[ $1 = "--bsd" ]]; then

	cat /teaOS/utils/license/licenses/bsd
else
	echo ""
fi
if [[ $1 = "--gpl" ]]; then
        
           cat /teaOS/utils/license/licenses/gnu
           else
           echo ""
           fi

if [[ $1 = "--help" ]]; then

	echo "license: A license viewer for teaOS"
	echo
	echo "Arguments:"
	echo
	echo "		--mit: Shows MIT License"
	echo "		--bsd: Shows BSD License"
        echo "          --gpl: Shows the GNU GPL v3"
        echo ""
else

	break

fi
